services:
  web:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/app
    ports:
      - "5154:5154"
    working_dir: /app/WebProject
    command: dotnet watch run
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: aleks
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: aleks_db
    ports:
      - "5432:5432"
    working_dir: /app/WebProject
#test
      
