services:
  web:
    image: mcr.microsoft.com/dotnet/sdk
    volumes:
      - .:/app
    ports:
      - "5144:5144"
    working_dir: /app/SideProject
    command: dotnet watch run --urls=http://0.0.0.0:5144
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: aleks
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: aleks_db
    ports:
      - "5132:5132"
    working_dir: /app/WebProject
      
